CREATE TABLE user_health_nutrition_profiles (
    user_id BIGINT PRIMARY KEY,
    gender VARCHAR(24) NOT NULL,
    age INT NOT NULL,
    height_cm DECIMAL(5,1) NOT NULL,
    weight_kg DECIMAL(5,1) NOT NULL,
    activity_level VARCHAR(24) NOT NULL,
    goal VARCHAR(24) NOT NULL,
    dietary_restrictions_json TEXT,
    allergies_json TEXT,
    special_health_condition VARCHAR(160),
    target_mode VARCHAR(24) NOT NULL DEFAULT 'DISABLED',
    ai_calories_kcal DECIMAL(8,2),
    ai_protein_g DECIMAL(8,2),
    ai_fat_g DECIMAL(8,2),
    ai_carbohydrate_g DECIMAL(8,2),
    ai_reference_basis VARCHAR(255),
    ai_reference_updated_at DATETIME,
    current_calories_kcal DECIMAL(8,2),
    current_protein_g DECIMAL(8,2),
    current_fat_g DECIMAL(8,2),
    current_carbohydrate_g DECIMAL(8,2),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_health_nutrition_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_health_nutrition_age CHECK (age >= 13 AND age <= 120),
    CONSTRAINT chk_health_nutrition_height CHECK (height_cm >= 100 AND height_cm <= 250),
    CONSTRAINT chk_health_nutrition_weight CHECK (weight_kg >= 25 AND weight_kg <= 300),
    CONSTRAINT chk_health_nutrition_target_mode CHECK (target_mode IN ('DISABLED', 'AI_REFERENCE', 'CUSTOM'))
);
