package com.example.food.weekly;

import com.example.food.common.GlobalExceptionHandler;
import com.example.food.security.AppRole;
import com.example.food.security.AuthPrincipal;
import com.example.food.security.JwtService;
import com.example.food.security.SecurityConfig;
import com.example.food.weekly.dto.WeeklyMenuResponse;
import com.example.food.weekly.dto.WeeklyShoppingStatusResponse;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.context.annotation.Import;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;

import java.time.LocalDate;
import java.util.List;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@WebMvcTest(WeeklyMenuController.class)
@Import({SecurityConfig.class, GlobalExceptionHandler.class})
class WeeklyMenuControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private JwtService jwtService;

    @MockBean
    private WeeklyMenuService service;

    @Test
    void userCanReadWeeklyMenu() throws Exception {
        authenticateUser();
        when(service.get(7L, LocalDate.of(2026, 8, 31))).thenReturn(
                new WeeklyMenuResponse(99L, LocalDate.of(2026, 8, 31), LocalDate.of(2026, 9, 6), List.of(), List.of())
        );

        mockMvc.perform(get("/api/users/me/weekly-menu")
                        .header("Authorization", "Bearer user-token")
                        .param("weekStart", "2026-08-31"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.id").value(99))
                .andExpect(jsonPath("$.data.weekStart").value("2026-08-31"));
    }

    @Test
    void userCanSaveWeeklyMenu() throws Exception {
        authenticateUser();
        when(service.save(org.mockito.ArgumentMatchers.eq(7L), any())).thenReturn(
                new WeeklyMenuResponse(99L, LocalDate.of(2026, 8, 31), LocalDate.of(2026, 9, 6), List.of(), List.of())
        );

        mockMvc.perform(put("/api/users/me/weekly-menu")
                        .header("Authorization", "Bearer user-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "weekStart": "2026-08-31",
                                  "items": [
                                    {
                                      "menuDate": "2026-08-31",
                                      "mealType": "DINNER",
                                      "recipeId": 1
                                    }
                                  ]
                                }
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.id").value(99));

        verify(service).save(org.mockito.ArgumentMatchers.eq(7L), any());
    }

    @Test
    void userCanRequestAutoGeneratedWeeklyMenu() throws Exception {
        authenticateUser();
        when(service.autoGenerate(org.mockito.ArgumentMatchers.eq(7L), any())).thenReturn(
                new WeeklyMenuResponse(99L, LocalDate.of(2026, 8, 31), LocalDate.of(2026, 9, 6), List.of(), List.of())
        );

        mockMvc.perform(post("/api/users/me/weekly-menu/auto-generate")
                        .header("Authorization", "Bearer user-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "weekStart": "2026-08-31",
                                  "overwrite": true
                                }
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.id").value(99));

        verify(service).autoGenerate(org.mockito.ArgumentMatchers.eq(7L), any());
    }

    @Test
    void userCanUpdateWeeklyShoppingStatus() throws Exception {
        authenticateUser();
        when(service.saveShoppingStatus(org.mockito.ArgumentMatchers.eq(7L), any())).thenReturn(
                new WeeklyShoppingStatusResponse("鸡蛋", "5个", false, "PURCHASING")
        );

        mockMvc.perform(put("/api/users/me/weekly-menu/shopping-status")
                        .header("Authorization", "Bearer user-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "weekStart": "2026-08-31",
                                  "ingredientName": "鸡蛋",
                                  "status": "PURCHASING"
                                }
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.ingredientName").value("鸡蛋"))
                .andExpect(jsonPath("$.data.status").value("PURCHASING"));

        verify(service).saveShoppingStatus(org.mockito.ArgumentMatchers.eq(7L), any());
    }

    @Test
    void invalidWeeklyMenuItemReturnsParameterError() throws Exception {
        authenticateUser();

        mockMvc.perform(put("/api/users/me/weekly-menu")
                        .header("Authorization", "Bearer user-token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {
                                  "weekStart": "2026-08-31",
                                  "items": [
                                    {
                                      "menuDate": "2026-08-31",
                                      "mealType": "SNACK",
                                      "recipeId": 1
                                    }
                                  ]
                                }
                                """))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message").value("Invalid request parameters"));
    }

    @Test
    void userCanClearWeeklyMenu() throws Exception {
        authenticateUser();

        mockMvc.perform(delete("/api/users/me/weekly-menu")
                        .header("Authorization", "Bearer user-token")
                        .param("weekStart", "2026-08-31"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data").doesNotExist());

        verify(service).delete(7L, LocalDate.of(2026, 8, 31));
    }

    private void authenticateUser() {
        when(jwtService.parseToken("user-token"))
                .thenReturn(new AuthPrincipal(7L, "13800138000", AppRole.USER));
    }
}
